print("I am Dip\"esh Chaudhary.")
print("I am from Nepal.")
print("I am B.Tech IT student.")
print("I lives in rented room.")
print("I am learning this programming language from Technology Channel.")
print("My permanent address is Bardiya.")
print("I am pationate to become a Ethical Hacker.")
print("I don't have much money to afford that course now.")
print("But I am continuously learning that from free sites.")
print("I am specifically learning that from TryHackMe platform.")